# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3559876745703748487949a4e27f649b"
name = "customfly-hasan"
application_url = "https://custom.duniasantri.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "uploadfly-lab.myshopify.com"

[webhooks]
api_version = "2026-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_orders,write_products"

[auth]
redirect_urls = [
  "https://custom.duniasantri.com/api/auth/callback"
]

[app_proxy]
url = "https://custom.duniasantri.com/imcst_api/proxy"
subpath = "customfly"
prefix = "apps"

[pos]
embedded = false
