api_version = "2026-01"

[[extensions]]
type = "ui_extension"
name = "Customfly Designer"
handle = "customfly-designer-action"

[[extensions.targeting]]
module = "./src/index.jsx"
target = "admin.product-details.action.render"
