[[extensions]]
uid = "e8095c54-7fe9-2c5b-dd3f-abaeda940e245d6c1c61"
type = "admin_link"
name = "Customfly Designer"
handle = "customfly-designer-action"

[[extensions.targeting]]
target = "admin.product-details.action.link"
url = "/designer/:id"
